export const movieContainer = [

    {
      id:1,
      title: "The Invisible Guest(2016)",
      description:  " Movie genre Crime- A successful entrepreneur accused of murder and a witness preparation expert to come up with an impregnable defense.",
      posterurl:"https://m.media-amazon.com/images/M/MV5BMDk0YzAwYjktMWFiZi00Y2FmLWJmMmMtMzUyZDZmMmU5MjkzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
      rate: 1,
      trailer: "https://www.imdb.com/video/vi1289008665?playlistId=tt4857264&ref_=tt_ov_vi",
    },
    {
      id:2,
      title: "Mirage (2018)",
      description: "Movie genre Drama/Fantasy/Mystery- Two storms separated by 25 years. A woman murdered. A daughter missed. Only 72 hours to discover the truth.",
      posterurl:"https://image.tmdb.org/t/p/original/6S2wECQuy4QKaGgKvialqBfnPBY.jpg",
      rate: 2,
      trailer: "https://www.imdb.com/video/vi3533748761?playlistId=tt6908274&ref_=tt_ov_vi",
    },
    { id:3,
      title: "Extraction(2020)",
      description: "Movie genre Action/Thriller- Tyler Rake, embarks on the most deadly extraction when he's enlisted to rescue the kidnapped son...",
      posterurl: "https://m.media-amazon.com/images/M/MV5BMDJiNzUwYzEtNmQ2Yy00NWE4LWEwNzctM2M0MjE0OGUxZTA3XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
      rate: 3,
      trailer: "https://www.imdb.com/video/vi1418378777?playlistId=tt8936646&ref_=tt_ov_vi",
    },
    { id:4,
      title: "Joker (2019)",
      description: "Movie genre Crime/Drama/Thriller- In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society...",
      posterurl: "https://images-na.ssl-images-amazon.com/images/I/71H4EDEfcwL._AC_SL1500_.jpg",
      rate: 4, 
      trailer: "https://www.imdb.com/video/vi1723318041?playlistId=tt7286456&ref_=tt_ov_vi",
    },
    { id:5,
      title: "The Social dilemma (2020)",
      description: "Movie genre Documentary- Explores the dangerous human impact of social networking, with tech experts...",
      posterurl: "https://secureservercdn.net/50.62.172.113/gvt.c8b.myftpupload.com/wp-content/uploads/2020/08/THE_SOCIAL_DILEMMA_MONSTER_HI_RES_JPEG-scaled.jpg",
      rate: 4,
      trailer: "https://www.imdb.com/video/vi306953753?playlistId=tt11464826&ref_=tt_ov_vi",
    },
    { id:6,
      title: "Avengers (2019)",
      description: "Action/Adventure/Drama- After the devastating events of Avengers 2018 the Avengers assemble once more in order to reverse Thanos' actions...",
      posterurl: "https://upload.wikimedia.org/wikipedia/en/4/4d/Avengers_Infinity_War_poster.jpg",
      rate: 5,
      trailer: "https://www.imdb.com/video/vi2163260441?playlistId=tt4154796&ref_=tt_ov_vi",
    },
  ];
   